# Generated by Django 5.1.1 on 2024-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_reputation', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('weight', models.FloatField()),
                ('material', models.IntegerField(choices=[(0, 'Aluminium'), (1, 'Brass'), (2, 'Bronze'), (3, 'Clay'), (4, 'Marble'), (5, 'Stone'), (6, 'Wood')])),
                ('price_of_sculpture', models.FloatField()),
                ('base_shipping_price', models.FloatField()),
                ('international', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('express_shipment', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('installation_included', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('transport', models.IntegerField(choices=[(0, 'Airways'), (1, 'Roadways'), (2, 'Waterways')])),
                ('fragile', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('customer_information', models.IntegerField(choices=[(0, 'Wealthy'), (1, 'Working Class')])),
                ('remote_location', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('scheduled_date', models.FloatField()),
            ],
        ),
    ]
